# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: yarn run build

      - setup_remote_docker:
          version: 19.03.13

      - run: docker build . -t toolbox

      - run: docker save -o public/toolbox.tar toolbox

      - deploy:
          name: deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" = 'master' ]; then
               sudo apt-get install -y rsync
               echo '10people.co.uk,139.59.197.112 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEC+H4axl5nWwKr683pS6R3P4vEvWQUjEWTrAosaPZXAbXOYEMLNB4G/xlmiJ5BIcE4S/IyKlM9wgSRyiBXAQ6k=' >> ~/.ssh/known_hosts
               # Copy everything over
               rsync -a public/ 10people.co.uk:~/completionist/
               # Import docker, delete docker tar, copy everything over to correct dir
               ssh 10people.co.uk "sudo docker load < ~/completionist/toolbox.tar && rm ~/completionist/toolbox.tar && sudo rsync -a ~/completionist/ /root/server/nginx/data/completionist"
               # Restart the docker image
               ssh 10people.co.uk sudo docker-compose -f /root/server/docker-compose.yml restart toolbox
            fi

